line-length = 88
# Assume the minimum python version
target-version = 'py312'
fix = true
exclude = ["*.pyi", "*/site-packages"]

############################
# lint rules
############################
[lint]
select = [
  "E",      # pycodestyle: Error
  "W",      # pycodestyle: Warning
  "F",      # Pyflakes
  "PLE",    # pylint: Error
  "B",      # flake8-bugbear
  "TC",     # flake8-type-checking
  "I",      # isort
  "T20",    # flake8-print
  "C4",     # flake8-comprehensions
  "UP",     # pyupgrade
  "ARG001", # unused arguments in functions
  # "ICN", # flake8-import-conventions
  # "PERF", # Perflint
  # "RUF",  # Ruff-specific rules
  # "TID",  # flake8-tidy-imports
  # "SIM",  # flake8-simplify
]
unfixable = [
  "F401", # unused imports
  "F841", # unused variables
]
ignore = [
  "B008", # do not perform function calls in argument defaults
]

[lint.per-file-ignores]
# E501: line too long, handled by formatter
"*.py" = ["E501"]
# `E402` (import violations)
"__init__.py" = ["E402"]
"examples/*" = ["E402"]
"tests/*" = ["E402"]

[lint.isort]
known-third-party = []
known-first-party = ["app", "scripts"]

############################
# format rules
############################
[format]
quote-style = "preserve"
